### ISSUE TITLE
Fails to migrate

### ISSUE THREAD

**Issue by n0101** [nstevens1040/MigrateGMusic2Spotify#1]
Running on WIndows, setup as instructed.  I have premium accounts on GPM and Spotify.  I provided my Spotify username and the following error occurs:

File "C:\Python38\lib\site-packages\gmusicapi\protocol\shared.py", line 216, in perform
    response.raise_for_status()
  File "C:\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mclients.googleapis.com/sj/v2.5/trackfeed?alt=json&include-tracks=true&updated-min=-1&hl=en_US&dv=0&tier=aa

During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "MigrateGMusic2Spotify.py", line 47, in <module>
    songs = api.get_all_songs()
  File "C:\Python38\lib\site-packages\gmusicapi\clients\mobileclient.py", line 278, in get_all_songs
    tracks = self._get_all_items(mobileclient.ListTracks, incremental,
  File "C:\Python38\lib\site-packages\gmusicapi\clients\mobileclient.py", line 2071, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "C:\Python38\lib\site-packages\gmusicapi\clients\mobileclient.py", line 2071, in <listcomp>
    return [s for chunk in generator for s in chunk]
  File "C:\Python38\lib\site-packages\gmusicapi\clients\mobileclient.py", line 2083, in _get_all_items_incremental
    lib_chunk = self._make_call(call,
  File "C:\Python38\lib\site-packages\gmusicapi\clients\mobileclient.py", line 43, in _make_call
    return super()._make_call(protocol, *args, **kwargs)
  File "C:\Python38\lib\site-packages\gmusicapi\clients\shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "C:\Python38\lib\site-packages\gmusicapi\protocol\shared.py", line 224, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: ListTracks: 500 Server Error: Internal Server Error for url: https://mclients.googleapis.com/sj/v2.5/trackfeed?alt=json&include-tracks=true&updated-min=-1&hl=en_US&dv=0&tier=aa
(requests kwargs: {'method': 'POST', 'url': 'https://mclients.googleapis.com/sj/v2.5/trackfeed', 'data': '{"max-results": "20000"}', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'params': {'alt': 'json', 'include-tracks': 'true', 'updated-min': -1, 'hl': 'en_US', 'dv': 0, 'tier': 'aa'}})
(response was: '{"error":{"errors":[{"domain":"global","reason":"backendError","message":"Backend Error"}],"code":500,"message":"Backend Error"}}')
```
I've seen the same error from other projects for GPM to Spotify migration.  The only thing I can think is the max-results being 20,000 and I have more than that in my GPM library?

**Comment by nstevens1040** [comment]
Hello n0101, I will look into this further. Thank you for letting me know, because I have limitations with regard to what I'm able to test. I started this project per request and was only able to add 1 song to my Google Play Music library before Google started moving forward with their decommissioning/deprecation process. I can say that other users have reported back, telling me that it worked for them, but they likely do not have >20,000 songs in their library. 

Nonetheless, I will look into this and see what others have said/done. Perhaps there is an alternative to the '.get_all_songs()' method that iterates differently and doesn't attempt to pull your entire library. Or maybe the 20,000 limitation is hard coded somewhere writable in the 'Mobileclient' module.
